#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleMapDemo.Resource", IsApplication=true)]

namespace SimpleMapDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monkey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int polarbear = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int animateButton = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int description = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int map = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int mapWithOverlay = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int title = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int zoomInButton = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int zoomOutButton = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BasicDemo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Feature = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MapLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MapWithOverlayLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int activity_label_mapwithmarkers = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int activity_label_samplemap = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int basic_map = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int basic_map_description = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int mapsAppText = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int mapsAppTextDescription = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int showMapActivityDescription = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int showMapWithOverlaysDescription = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int streetViewText = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
